version: '3'

services:
  osm:
    image: overv/openstreetmap-tile-server
    volumes:
      - ./osm-data:/data/database/
      - ./osm-tiles:/data/tiles/
    ports:
      - "8181:80"
      - "5433:5432"
    command: "run"
    networks:
      - n7m_osm_bridge
volumes:
  osm-data:
  osm-tiles:

networks:
  n7m_osm_bridge:
    external: true
